### ISSUE TITLE
Reverse polarity protection / ferrite beads?

### ISSUE THREAD

**Issue by tsujigiri** [TomWhitwell/TH-VCO1#1]
Hi,
please excuse my noob question, but I'm having a bit of trouble interpreting the schematic. I get the idea behind the combination of a diode and a fuse as a protection against reverse polarity. I'm a bit thrown off by the "Ferrites: XXX or XXX" part, though. This isn't part of the reverse polarity protection but protection against HF noise, right? Is this meant to be an either/or type of situation?

Cheers!

**Comment by TomWhitwell** [comment]
That's the idea - the ferrites are for noise. 

I think there's an element of Cargo Cult design to some of this stuff...
